#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit documentary staging against the canonical public CorBo index.

Read-only. Uses docs/data/corbo-units.json generated by build_corpus_indexes.py.
No staging row is promoted or modified.
"""
from __future__ import annotations
import csv,json,re,unicodedata
from collections import defaultdict
from difflib import SequenceMatcher
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
PUBLIC=ROOT/"docs/data/corbo-units.json"
STAGING=[
 ("Pemo — Baraedugume",ROOT/"CorBo_vNext/texts/pemo-baraedugume/pemo_baraedugume_editorial.tsv"),
 ("Pemo — Coqueiro",ROOT/"CorBo_vNext/texts/pemo-coqueiro/pemo_coqueiro_editorial.tsv"),
 ("Arquivo — novos testemunhos",ROOT/"CorBo_vNext/texts/archive-additions/archive_additions_editorial.tsv"),
]

def norm(s):
 s=unicodedata.normalize("NFC",str(s or "")).casefold().replace("\\n"," ")
 s=re.sub(r"[^a-záéíóúâêôãõçüñ]+"," ",s)
 return " ".join(s.split())

def read_tsv(p):
 with p.open(encoding="utf-8",newline="") as f:return list(csv.DictReader(f,delimiter="\t"))

if not PUBLIC.exists():
 raise SystemExit("Índice público ausente. Rode primeiro: python3 scripts/build_corpus_indexes.py")
public=json.loads(PUBLIC.read_text(encoding="utf-8"))
targets=[]
exact=defaultdict(list)
for u in public:
 for field in ("b","source"):
  n=norm(u.get(field,""))
  if not n:continue
  item=(n,u.get("id",""),u.get("collection",""),field)
  targets.append(item);exact[n].append(item)

grand={"exact":0,"candidate":0,"unmatched":0}
print("AUDITORIA STAGING × CORPUS PÚBLICO")
print("Critério: exact = igualdade normalizada; candidate >=0.99 = revisão humana; nenhum resultado é gravado.\n")
for label,path in STAGING:
 rows=read_tsv(path);counts={"exact":0,"candidate":0,"unmatched":0};cands=[]
 for r in rows:
  src=(r.get("reviewed") or r.get("source") or "").strip();n=norm(src)
  if n and n in exact:
   counts["exact"]+=1;continue
  best=(0.0,None)
  if n:
   for t,uid,coll,field in targets:
    ratio=len(n)/len(t)
    if ratio<0.65 or ratio>1.55:continue
    score=SequenceMatcher(None,n,t,autojunk=False).ratio()
    if score>best[0]:best=(score,(uid,coll,field))
  if best[0]>=0.99:
   counts["candidate"]+=1
   cands.append((r.get("id",""),best[0],best[1]))
  else:counts["unmatched"]+=1
 for k in grand:grand[k]+=counts[k]
 print(f"{label}: {len(rows)}")
 print(f"  exact: {counts['exact']}")
 print(f"  candidate >=0.99: {counts['candidate']}")
 print(f"  unmatched: {counts['unmatched']}")
 for sid,score,(uid,coll,field) in cands[:30]:
  print(f"    {sid} => {uid} [{score:.3f}; {coll}; {field}]")
 print()
print("TOTAL")
print(f"  staging: {sum(grand.values())}")
print(f"  exact: {grand['exact']}")
print(f"  candidate >=0.99: {grand['candidate']}")
print(f"  unmatched: {grand['unmatched']}")
print("\nATENÇÃO: unmatched significa apenas 'sem correspondência textual forte'; não significa automaticamente 'unidade nova'.")
