#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Conservative matching of staged archive witnesses against Historia Mitica collation."""
import csv,re,unicodedata
from difflib import SequenceMatcher
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
W=ROOT/"CorBo_vNext/texts/historia-mitica/archive_parallel_witnesses.tsv"
C=ROOT/"CorBo_vNext/texts/historia-mitica/historia_mitica_collation.tsv"

def norm(s):
 s=unicodedata.normalize("NFC",s or "").lower()
 s=s.replace("\\n"," ")
 s=re.sub(r"[^a-záéíóúâêôãõçüñ]+"," ",s)
 return " ".join(s.split())

with W.open(encoding="utf-8") as f: wr=list(csv.DictReader(f,delimiter="\t"))
with C.open(encoding="utf-8") as f: cr=list(csv.DictReader(f,delimiter="\t"))
targets=[]
for r in cr:
 for field in ("witness_a","witness_b","reviewed"):
  n=norm(r.get(field,""))
  if n: targets.append((n,r["id"],field))
exact={}
for n,i,field in targets: exact.setdefault(n,[]).append((i,field))
counts={"confirmed":0,"exact":0,"candidate":0,"unmatched":0}
for r in wr:
 # Human decisions are authoritative and survive later matcher runs.
 if r.get("collation_status")=="confirmed":
  counts["confirmed"]+=1
  continue
 # Remove only notes generated by previous matcher runs, so reruns are idempotent.
 note=r.get("editorial_note","")
 note=re.sub(r"(?:\s*Exact normalized Bororo match\.)+$","",note)
 note=re.sub(r"(?:\s*High-similarity candidate \([0-9.]+\); requires human confirmation\.)+$","",note)
 r["editorial_note"]=note.strip()
 n=norm(r["source"])
 if n in exact:
  hits=exact[n]
  ids=sorted(set(i for i,_ in hits))
  r["collation_status"]="exact"
  r["corbo_match_id"]=";".join(ids)
  r["editorial_note"]=(r["editorial_note"]+" " if r["editorial_note"] else "")+"Exact normalized Bororo match."
  counts["exact"]+=1
  continue
 best=(0.0,None,None)
 if n:
  # Cheap length filter prevents unrelated long/short comparisons.
  for t,i,field in targets:
   ratio=len(n)/len(t)
   if ratio<0.65 or ratio>1.55: continue
   score=SequenceMatcher(None,n,t,autojunk=False).ratio()
   if score>best[0]: best=(score,i,field)
 # In highly formulaic passages, ~0.90 can match the wrong named participant.
 # Require near-identity for automatic candidate surfacing; lower scores remain
 # unmatched for later structure/name-aware collation.
 if best[0]>=0.99:
  r["collation_status"]="candidate"
  r["corbo_match_id"]=best[1]
  r["editorial_note"]=(r["editorial_note"]+" " if r["editorial_note"] else "")+f"High-similarity candidate ({best[0]:.3f}); requires human confirmation."
  counts["candidate"]+=1
 else:
  r["collation_status"]="unmatched"; r["corbo_match_id"]=""
  counts["unmatched"]+=1
with W.open("w",encoding="utf-8",newline="") as f:
 w=csv.DictWriter(f,fieldnames=wr[0].keys(),delimiter="\t",lineterminator="\n");w.writeheader();w.writerows(wr)
print("Matching concluído:",counts)
print("Somente exact é correspondência automática; candidate (>=0.99) exige revisão humana.")


# Diagnostic only: inspect unresolved witnesses using their nearest textual candidates.
# This does not write or promote any additional match.
unresolved=[r for r in wr if r["collation_status"]=="unmatched"]
diag=[]
for r in unresolved:
 n=norm(r["source"])
 best=[]
 if n:
  for t,i,field in targets:
   ratio=len(n)/len(t)
   if ratio<0.45 or ratio>2.20: continue
   score=SequenceMatcher(None,n,t,autojunk=False).ratio()
   if score>=0.60: best.append((score,i,field))
 best=sorted(best,reverse=True)[:3]
 if best:
  diag.append((r["witness_id"],r["document"],[(round(s,3),i,f) for s,i,f in best]))
print("Unmatched com candidato >=0.60:",len(diag))
for wid,doc,best in diag:
 print(wid,"|",doc,"|",best)


# Sequence-anchor diagnostic. Strong matches define ordered anchors; unresolved
# units are proposed only when they fall between two anchors whose target IDs
# preserve the same one-to-one offset. Nothing is written automatically.
def uid_num(s):
 m=re.search(r"-u(\\d+)$",s or "")
 return int(m.group(1)) if m else None

by_doc={}
for idx,r in enumerate(wr):
 by_doc.setdefault(r["document"],[]).append((idx,r))
seq=[]
for doc,items in by_doc.items():
 anchors=[]
 for pos,(global_i,r) in enumerate(items):
  if r["collation_status"] in ("exact","candidate","confirmed") and ";" not in r["corbo_match_id"]:
   u=uid_num(r["corbo_match_id"])
   if u is not None: anchors.append((pos,u,r["witness_id"]))
 for (p1,u1,w1),(p2,u2,w2) in zip(anchors,anchors[1:]):
  gap=p2-p1
  if gap<=1 or u2-u1!=gap: continue
  for p in range(p1+1,p2):
   rr=items[p][1]
   if rr["collation_status"]=="unmatched":
    seq.append((rr["witness_id"],f"BOR-CORBO-HM001-u{u1+(p-p1):03d}",w1,w2))
print("Propostas por sequência entre âncoras:",len(seq))
for wid,target,left,right in seq:
 print(wid,"=>",target,"| anchors",left,right)


# REVIEW REPORT: human-readable context for near-identical candidates.
# Diagnostic only; it does not change collation status.
by_id={r["id"]:r for r in cr}
candidates=[r for r in wr if r.get("collation_status")=="candidate"]
print("Candidatos para revisão humana:",len(candidates))
for r in candidates:
 target=by_id.get(r.get("corbo_match_id",""),{})
 source=r.get("source","")
 variants=[("witness_a",target.get("witness_a","")),("witness_b",target.get("witness_b","")),("reviewed",target.get("reviewed",""))]
 scored=[(SequenceMatcher(None,norm(source),norm(v),autojunk=False).ratio(),field,v) for field,v in variants if norm(v)]
 scored.sort(reverse=True)
 score,field,target_text=scored[0] if scored else (0.0,"","")
 print("\n###",r["witness_id"],"=>",r.get("corbo_match_id",""),f"[{score:.3f}; {field}]")
 print("DOCUMENTO:",r.get("document",""),"| SEÇÃO:",r.get("section",""))
 print("ARQUIVO :",source.replace("\n"," "))
 print("CORBO   :",target_text.replace("\n"," "))
 print("PORTUGUÊS:",r.get("portuguese","").replace("\n"," "))
