#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Conservative matching of staged archive witnesses against Historia Mitica collation."""
import csv,re,unicodedata
from difflib import SequenceMatcher
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
W=ROOT/"CorBo_vNext/texts/historia-mitica/archive_parallel_witnesses.tsv"
C=ROOT/"CorBo_vNext/texts/historia-mitica/historia_mitica_collation.tsv"

def norm(s):
 s=unicodedata.normalize("NFC",s or "").lower()
 s=s.replace("\\n"," ")
 s=re.sub(r"[^a-záéíóúâêôãõçüñ]+"," ",s)
 return " ".join(s.split())

with W.open(encoding="utf-8") as f: wr=list(csv.DictReader(f,delimiter="\t"))
with C.open(encoding="utf-8") as f: cr=list(csv.DictReader(f,delimiter="\t"))
targets=[]
for r in cr:
 for field in ("witness_a","witness_b","reviewed"):
  n=norm(r.get(field,""))
  if n: targets.append((n,r["id"],field))
exact={}
for n,i,field in targets: exact.setdefault(n,[]).append((i,field))
counts={"confirmed":0,"exact":0,"candidate":0,"unmatched":0}
for r in wr:
 # Human decisions are authoritative and survive later matcher runs.
 if r.get("collation_status")=="confirmed":
  counts["confirmed"]+=1
  continue
 # Remove only notes generated by previous matcher runs, so reruns are idempotent.
 note=r.get("editorial_note","")
 note=re.sub(r"(?:\s*Exact normalized Bororo match\.)+$","",note)
 note=re.sub(r"(?:\s*High-similarity candidate \([0-9.]+\); requires human confirmation\.)+$","",note)
 r["editorial_note"]=note.strip()
 n=norm(r["source"])
 if n in exact:
  hits=exact[n]
  ids=sorted(set(i for i,_ in hits))
  r["collation_status"]="exact"
  r["corbo_match_id"]=";".join(ids)
  r["editorial_note"]=(r["editorial_note"]+" " if r["editorial_note"] else "")+"Exact normalized Bororo match."
  counts["exact"]+=1
  continue
 best=(0.0,None,None)
 if n:
  # Cheap length filter prevents unrelated long/short comparisons.
  for t,i,field in targets:
   ratio=len(n)/len(t)
   if ratio<0.65 or ratio>1.55: continue
   score=SequenceMatcher(None,n,t,autojunk=False).ratio()
   if score>best[0]: best=(score,i,field)
 # In highly formulaic passages, ~0.90 can match the wrong named participant.
 # Require near-identity for automatic candidate surfacing; lower scores remain
 # unmatched for later structure/name-aware collation.
 if best[0]>=0.99:
  r["collation_status"]="candidate"
  r["corbo_match_id"]=best[1]
  r["editorial_note"]=(r["editorial_note"]+" " if r["editorial_note"] else "")+f"High-similarity candidate ({best[0]:.3f}); requires human confirmation."
  counts["candidate"]+=1
 else:
  r["collation_status"]="unmatched"; r["corbo_match_id"]=""
  counts["unmatched"]+=1
with W.open("w",encoding="utf-8",newline="") as f:
 w=csv.DictWriter(f,fieldnames=wr[0].keys(),delimiter="\t",lineterminator="\n");w.writeheader();w.writerows(wr)
print("Matching concluído:",counts)
print("Somente exact é correspondência automática; candidate (>=0.99) exige revisão humana.")


# Diagnostic only: inspect unresolved witnesses using their nearest textual candidates.
# This does not write or promote any additional match.
unresolved=[r for r in wr if r["collation_status"]=="unmatched"]
diag=[]
for r in unresolved:
 n=norm(r["source"])
 best=[]
 if n:
  for t,i,field in targets:
   ratio=len(n)/len(t)
   if ratio<0.45 or ratio>2.20: continue
   score=SequenceMatcher(None,n,t,autojunk=False).ratio()
   if score>=0.60: best.append((score,i,field))
 best=sorted(best,reverse=True)[:3]
 if best:
  diag.append((r["witness_id"],r["document"],[(round(s,3),i,f) for s,i,f in best]))
print("Unmatched com candidato >=0.60:",len(diag))
for wid,doc,best in diag:
 print(wid,"|",doc,"|",best)


# Sequence-anchor diagnostic. Strong matches define ordered anchors; unresolved
# units are proposed only when they fall between two anchors whose target IDs
# preserve the same one-to-one offset. Nothing is written automatically.
def uid_num(s):
 m=re.search(r"-u(\\d+)$",s or "")
 return int(m.group(1)) if m else None

by_doc={}
for idx,r in enumerate(wr):
 by_doc.setdefault(r["document"],[]).append((idx,r))
seq=[]
for doc,items in by_doc.items():
 anchors=[]
 for pos,(global_i,r) in enumerate(items):
  if r["collation_status"] in ("exact","candidate","confirmed") and ";" not in r["corbo_match_id"]:
   u=uid_num(r["corbo_match_id"])
   if u is not None: anchors.append((pos,u,r["witness_id"]))
 for (p1,u1,w1),(p2,u2,w2) in zip(anchors,anchors[1:]):
  gap=p2-p1
  if gap<=1 or u2-u1!=gap: continue
  for p in range(p1+1,p2):
   rr=items[p][1]
   if rr["collation_status"]=="unmatched":
    seq.append((rr["witness_id"],f"BOR-CORBO-HM001-u{u1+(p-p1):03d}",w1,w2))
print("Propostas por sequência entre âncoras:",len(seq))
for wid,target,left,right in seq:
 print(wid,"=>",target,"| anchors",left,right)


# REVIEW REPORT: human-readable context for near-identical candidates.
# Diagnostic only; it does not change collation status.
by_id={r["id"]:r for r in cr}
candidates=[r for r in wr if r.get("collation_status")=="candidate"]
print("Candidatos para revisão humana:",len(candidates))
for r in candidates:
 target=by_id.get(r.get("corbo_match_id",""),{})
 source=r.get("source","")
 variants=[("witness_a",target.get("witness_a","")),("witness_b",target.get("witness_b","")),("reviewed",target.get("reviewed",""))]
 scored=[(SequenceMatcher(None,norm(source),norm(v),autojunk=False).ratio(),field,v) for field,v in variants if norm(v)]
 scored.sort(reverse=True)
 score,field,target_text=scored[0] if scored else (0.0,"","")
 print("\n###",r["witness_id"],"=>",r.get("corbo_match_id",""),f"[{score:.3f}; {field}]")
 print("DOCUMENTO:",r.get("document",""),"| SEÇÃO:",r.get("section",""))
 print("ARQUIVO :",source.replace("\n"," "))
 print("CORBO   :",target_text.replace("\n"," "))
 print("PORTUGUÊS:",r.get("portuguese","").replace("\n"," "))


# REVIEW REPORT: exact normalized matches, for optional human audit.
# These are already automatic matches; this report lets the editor/reviewer
# verify witness identity and named participants before promoting to confirmed.
exacts=[r for r in wr if r.get("collation_status")=="exact"]
print("\nExact para auditoria humana:",len(exacts))
for r in exacts:
 ids=[i.strip() for i in r.get("corbo_match_id","").split(";") if i.strip()]
 for target_id in ids:
  target=by_id.get(target_id,{})
  source=r.get("source","")
  variants=[("witness_a",target.get("witness_a","")),("witness_b",target.get("witness_b","")),("reviewed",target.get("reviewed",""))]
  scored=[(SequenceMatcher(None,norm(source),norm(v),autojunk=False).ratio(),field,v) for field,v in variants if norm(v)]
  scored.sort(reverse=True)
  score,field,target_text=scored[0] if scored else (0.0,"","")
  print("\n### EXACT",r["witness_id"],"=>",target_id,f"[{score:.3f}; {field}]")
  print("DOCUMENTO:",r.get("document",""),"| SEÇÃO:",r.get("section",""))
  print("ARQUIVO :",source.replace("\n"," "))
  print("CORBO   :",target_text.replace("\n"," "))
  print("PORTUGUÊS:",r.get("portuguese","").replace("\n"," "))


# RARE-ANCHOR DIAGNOSTIC: unresolved units sharing distinctive lexical material.
# Candidate generation only. It never writes a match or changes a status.
from collections import Counter,defaultdict
def toks(s):
 return [x for x in norm(s).split() if len(x)>=4]

target_docs={}
df=Counter()
for rr in cr:
 bag=set()
 for field in ("witness_a","witness_b","reviewed"):
  bag.update(toks(rr.get(field,"")))
 target_docs[rr["id"]]=bag
 for t in bag:df[t]+=1

inv=defaultdict(set)
for tid,bag in target_docs.items():
 for t in bag:
  if df[t]<=6:inv[t].add(tid)

rare_diag=[]
for r in wr:
 if r.get("collation_status")!="unmatched":continue
 st=set(toks(r.get("source","")))
 rare=sorted((t for t in st if t in inv),key=lambda t:(df[t],-len(t),t))
 cand=defaultdict(list)
 for t in rare:
  for tid in inv[t]:cand[tid].append(t)
 scored=[]
 for tid,shared in cand.items():
  # Require at least two rare anchors, or one exceptionally rare long anchor.
  strong=len(shared)>=2 or any(df[t]==1 and len(t)>=7 for t in shared)
  if not strong:continue
  overlap=sum(1.0/df[t] for t in shared)
  scored.append((overlap,len(shared),tid,sorted(shared,key=lambda t:(df[t],-len(t),t))))
 scored.sort(reverse=True)
 if scored:
  rare_diag.append((r["witness_id"],r.get("document",""),scored[:3]))
print("\nUnmatched com âncoras lexicais raras:",len(rare_diag))
for wid,doc,best in rare_diag:
 print("\n### ANCHOR",wid,"|",doc)
 for score,n,tid,shared in best:
  print("=>",tid,f"[peso={score:.3f}; âncoras={n}]","; ".join(f"{t}(df={df[t]})" for t in shared[:12]))


# WINDOW DIAGNOSTIC: 2-5 consecutive unresolved witness units -> one CorBo unit.
# Useful when archival segmentation is finer than the existing collation.
# Diagnostic only: no TSV fields or statuses are changed.
target_variants={}
for rr in cr:
 vv=[]
 for field in ("witness_a","witness_b","reviewed"):
  n=norm(rr.get(field,""))
  if n:vv.append((field,n))
 target_variants[rr["id"]]=vv

window_diag=[]
for doc,items in by_doc.items():
 for start in range(len(items)):
  if items[start][1].get("collation_status")!="unmatched":continue
  parts=[]
  for end in range(start,min(len(items),start+5)):
   rr=items[end][1]
   if rr.get("collation_status")!="unmatched":break
   parts.append(rr.get("source",""))
   if len(parts)<2:continue
   joined=norm(" ".join(parts))
   if not joined:continue
   best=(0.0,None,None)
   for tid,vv in target_variants.items():
    for field,t in vv:
     ratio=len(joined)/len(t)
     if ratio<0.60 or ratio>1.65:continue
     s=SequenceMatcher(None,joined,t,autojunk=False).ratio()
     if s>best[0]:best=(s,tid,field)
   # Compare against the strongest individual unit -> same target.
   indiv=0.0
   if best[1]:
    vv=target_variants[best[1]]
    for p in parts:
     pn=norm(p)
     for _,t in vv:
      if pn and t:indiv=max(indiv,SequenceMatcher(None,pn,t,autojunk=False).ratio())
   gain=best[0]-indiv
   # High combined similarity plus meaningful gain indicates segmentation mismatch.
   if best[0]>=0.82 and gain>=0.08:
    ids=[items[p][1]["witness_id"] for p in range(start,end+1)]
    window_diag.append((best[0],gain,doc,ids,best[1],best[2]))

# Keep strongest non-identical proposals first; report only a manageable review set.
window_diag.sort(reverse=True)
print("\nJanelas testemunhais fortes (2-5 -> 1 CorBo):",len(window_diag))
for score,gain,doc,ids,tid,field in window_diag[:80]:
 print(f"{ids[0]}–{ids[-1]} => {tid} [sim={score:.3f}; ganho={gain:.3f}; {field}] | {doc}")


# STRONG-ANCHOR REVIEW: full side-by-side text for unusually distinctive anchors.
# Conservative review surface only; never changes matches.
strong_anchor=[]
for r in wr:
 if r.get("collation_status")!="unmatched":continue
 st=set(toks(r.get("source","")))
 cand=defaultdict(list)
 for t in st:
  if t in inv:
   for tid in inv[t]:cand[tid].append(t)
 for tid,shared in cand.items():
  unique=[t for t in shared if df[t]==1]
  rare=[t for t in shared if df[t]<=3]
  # Strong means >=2 corpus-unique anchors, or >=3 rare anchors with one unique.
  if len(unique)>=2 or (len(rare)>=3 and len(unique)>=1):
   weight=sum(1.0/df[t] for t in shared)
   strong_anchor.append((weight,len(unique),len(rare),r,tid,shared))
strong_anchor.sort(key=lambda x:(x[0],x[1],x[2]),reverse=True)
print("\nCandidatos fortes por âncora para revisão:",len(strong_anchor))
for weight,nu,nr,r,tid,shared in strong_anchor[:60]:
 target=by_id.get(tid,{})
 variants=[("witness_a",target.get("witness_a","")),("witness_b",target.get("witness_b","")),("reviewed",target.get("reviewed",""))]
 variants=[(field,v) for field,v in variants if norm(v)]
 # Show the target variant with greatest lexical overlap, not necessarily edit similarity.
 bestfield,besttext=max(variants,key=lambda fv:len(set(toks(fv[1])) & set(toks(r.get("source",""))))) if variants else ("","")
 anchors=sorted(shared,key=lambda t:(df[t],-len(t),t))
 print("\n### STRONG",r["witness_id"],"=>",tid,f"[peso={weight:.3f}; únicos={nu}; raros={nr}; {bestfield}]")
 print("DOCUMENTO:",r.get("document",""),"| SEÇÃO:",r.get("section",""))
 print("ÂNCORAS :","; ".join(f"{t}(df={df[t]})" for t in anchors))
 print("ARQUIVO :",r.get("source","").replace("\n"," "))
 print("CORBO   :",besttext.replace("\n"," "))
 print("PT ARQ. :",r.get("portuguese","").replace("\n"," "))
 print("PT CORBO:",target.get("portuguese","").replace("\n"," "))
